import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navber from "./components/navber/Navber";
import Footer from "./components/footer/Footer";
import CardsProvider from "./context/CardContext";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/*  className="min-h-full flex flex-col" */}
      <body cz-shortcut-listen="true">
        <CardsProvider>
          <Navber></Navber>
          <div>
            {children}
          </div>
          <Footer></Footer>
          {/*  */}
          <ToastContainer />
        </CardsProvider>
      </body>
    </html>
  );
}
